# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replicator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='replicator.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10replicator.proto\"@\n\x07Request\x12\x10\n\x08org_name\x18\x01 \x01(\t\x12\x13\n\x0bmin_version\x18\x02 \x01(\t\x12\x0e\n\x06images\x18\x03 \x03(\t\"6\n\x11ReplicationStatus\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x02\";\n\x0b\x44ockerImage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x11\n\tdocker_id\x18\x03 \x01(\t2\x9c\x01\n\nReplicator\x12\x34\n\x10StartReplication\x12\x08.Request\x1a\x12.ReplicationStatus\"\x00\x30\x01\x12(\n\nListImages\x12\x08.Request\x1a\x0c.DockerImage\"\x00\x30\x01\x12.\n\x10\x44ownloadedImages\x12\x08.Request\x1a\x0c.DockerImage\"\x00\x30\x01\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='org_name', full_name='Request.org_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_version', full_name='Request.min_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='Request.images', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=84,
)


_REPLICATIONSTATUS = _descriptor.Descriptor(
  name='ReplicationStatus',
  full_name='ReplicationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ReplicationStatus.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='progress', full_name='ReplicationStatus.progress', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=140,
)


_DOCKERIMAGE = _descriptor.Descriptor(
  name='DockerImage',
  full_name='DockerImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DockerImage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='DockerImage.tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='docker_id', full_name='DockerImage.docker_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['ReplicationStatus'] = _REPLICATIONSTATUS
DESCRIPTOR.message_types_by_name['DockerImage'] = _DOCKERIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'replicator_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)

ReplicationStatus = _reflection.GeneratedProtocolMessageType('ReplicationStatus', (_message.Message,), dict(
  DESCRIPTOR = _REPLICATIONSTATUS,
  __module__ = 'replicator_pb2'
  # @@protoc_insertion_point(class_scope:ReplicationStatus)
  ))
_sym_db.RegisterMessage(ReplicationStatus)

DockerImage = _reflection.GeneratedProtocolMessageType('DockerImage', (_message.Message,), dict(
  DESCRIPTOR = _DOCKERIMAGE,
  __module__ = 'replicator_pb2'
  # @@protoc_insertion_point(class_scope:DockerImage)
  ))
_sym_db.RegisterMessage(DockerImage)



_REPLICATOR = _descriptor.ServiceDescriptor(
  name='Replicator',
  full_name='Replicator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=204,
  serialized_end=360,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartReplication',
    full_name='Replicator.StartReplication',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLICATIONSTATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListImages',
    full_name='Replicator.ListImages',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_DOCKERIMAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DownloadedImages',
    full_name='Replicator.DownloadedImages',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_DOCKERIMAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPLICATOR)

DESCRIPTOR.services_by_name['Replicator'] = _REPLICATOR

# @@protoc_insertion_point(module_scope)
